version: "3.7"
services:
  client:
    build:
      context: ./client
      target: dev
    ports:
      - 8080:8080
    volumes:
      - ./client/src:/app/src
  api:
    build:
      context: ./api
      target: dev
    ports:
      - 3030:3030
    volumes:
      - ./api/src:/app/src
      - ./api/config:/app/config