version: "3.7"
services:
  client:
    build:
      context: ./client
      target: prod
    environment:
      - NODE_ENV=production
  api:
    build:
      context: ./api
      target: prod
    environment: 
      - NODE_ENV=production